controller_list:
  - name: fake_gp7_arm_controller
    joints:
      - joint_1_s
      - joint_2_l
      - joint_3_u
      - joint_4_r
      - joint_5_b
      - joint_6_t
  - name: fake_gp7_gripper_controller
    joints:
      - joint_6_t