gazebo_ros_control:
    joints:
      - joint_1_s
      - joint_2_l
      - joint_3_u
      - joint_4_r
      - joint_5_b
      - joint_6_t
    #if we didn't specify  PID values,gazebo_ros_control will be controled with gazebo methods.
    #if we specified PID values,we should set the true PID values with inertial_matrix,but it is very difficlut.
    #It is better not to put any PID in the yaml file rather than putting the wrong value. 
    #Just ingore the output:"No p gain specified for pid.  Namespace: "
    #To find suitable PID values use:http://wiki.ros.org/dynamic_reconfigure/Tutorials
    #https://answers.ros.org/question/293830/what-is-the-fix-for-no-p-gain-specified-for-pid-namespace-gazebo_ros_controlpid_gainsback_right_wheel_joint-ros-melodic/
    #https://github.com/ros-simulation/gazebo_ros_pkgs/issues/612
    # pid_gains:
    #   joint_1_s:   {p: 1000.0, i: 0.0, d: 0.0, i_clamp: 0.0}
    #   joint_2_l:   {p: 1000.0, i: 0.0, d: 0.0, i_clamp: 0.0}
    #   joint_3_u:   {p: 1000.0, i: 0.0, d: 0.0, i_clamp: 0.0}
    #   joint_4_r:   {p: 1000.0, i: 0.0, d: 0.0, i_clamp: 0.0}
    #   joint_5_b:   {p: 1000.0, i: 0.0, d: 0.0, i_clamp: 0.0}
    #   joint_6_t:   {p: 1000.0, i: 0.0, d: 0.0, i_clamp: 0.0}
